package com.novoda.merlin.test;

import java.io.File;

import org.junit.runners.model.InitializationError;

import org.robolectric.AndroidManifest;
import org.robolectric.RobolectricContext;
import org.robolectric.RobolectricTestRunner;

/**
 * Use this runner instead of RobolectricTestRunner with @RunWith annotation.
 */
public class Runner extends RobolectricTestRunner {

    // AUTOGENERATED: remove this line if you don't want 'java-robolectric' plugin to touch this file

    public Runner(final Class<?> testClass) throws InitializationError {
        super(RobolectricContext.bootstrap(Runner.class, testClass, new RobolectricContext.Factory() {
            @Override
            public RobolectricContext create() {
                return new RobolectricContext() {
                    @Override
                    protected AndroidManifest createAppManifest() {
                        return new AndroidManifest(new File("build/tmp/android"));
                    }
                };
            }
        }));
    }

}
